driver:
  name: vagrant
  synced_folders:
    - ["seedjob/", "/opt/seedjob"]
  customize:
    cpus: 2
    memory: 2048
  network:
    - - forwarded_port
      - guest: 80
        host: 9090
        auto_correct: true
    - - forwarded_port
      - guest: 8080
        host: 9091
        auto_correct: true

platforms:
  - name: centos-7.4
    run_list:
      - yum::default
      - jenkins::java

provisioner:
    name: chef_zero
    require_chef_omnibus: true

suites:
  - name: jenkins-chef-dsl
    run_list:
      - jenkins-chef-dsl::default
      - jenkins-chef-dsl::proxy
        #- jenkins-chef-dsl::artifactory
    attributes:
      jenkins:
        master:
          host: localhost
          install_method: package
